version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: bash -c "cd /usr/src/app && alembic -c alembic.ini upgrade head && uvicorn src.sms.adapters.entry_points.api.app:app --host 0.0.0.0 --port 8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/postgres

  db:
    image: 'bitnami/postgresql:latest'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"


volumes:
  db_data:
